# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccoverage < Formula
  desc "Coverage analysis for Claude Code project configuration"
  homepage "https://github.com/ShuhaoZQGG/ccoverage"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.12/ccoverage_0.0.12_darwin_amd64.tar.gz"
      sha256 "214ae6107dd9d8720aaae0c1c456367a75835f9659b9406a28f2e2e7a2d6d9ba"

      define_method(:install) do
        bin.install "ccoverage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.12/ccoverage_0.0.12_darwin_arm64.tar.gz"
      sha256 "563724cd09abd24981b4e98d8387433c4f769e23198929bfa3b6b6f92783ee49"

      define_method(:install) do
        bin.install "ccoverage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.12/ccoverage_0.0.12_linux_amd64.tar.gz"
      sha256 "62c3c415b0bf2949f5d62763dafd4719d7f9b5d138dfb23e4e9880a471f01778"
      define_method(:install) do
        bin.install "ccoverage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.12/ccoverage_0.0.12_linux_arm64.tar.gz"
      sha256 "63ac48114e24a86c3643fa3465569198f9e8ed8d7e25af2ff7076c4ee8d5654d"
      define_method(:install) do
        bin.install "ccoverage"
      end
    end
  end

  test do
    system "#{bin}/ccoverage", "--version"
  end
end
