# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccoverage < Formula
  desc "Coverage analysis for Claude Code project configuration"
  homepage "https://github.com/ShuhaoZQGG/ccoverage"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.9/ccoverage_0.0.9_darwin_amd64.tar.gz"
      sha256 "6e1baaaadf2a620f07686577787851cdb70f1f9e9e0006d72c7549f7676124f2"

      define_method(:install) do
        bin.install "ccoverage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.9/ccoverage_0.0.9_darwin_arm64.tar.gz"
      sha256 "8ccc4ab4e530455d1f9f6eb4706c95fd140fbe486fe2e720a8d03f3e3fdd9b44"

      define_method(:install) do
        bin.install "ccoverage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.9/ccoverage_0.0.9_linux_amd64.tar.gz"
      sha256 "0c820fb6e659580d92cb5e8254c4c946498064fd100d197ece53e207dfde50e1"
      define_method(:install) do
        bin.install "ccoverage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.9/ccoverage_0.0.9_linux_arm64.tar.gz"
      sha256 "1b67a04b665a367ac69831e39f6119ddbba3a0a14e024f6b3f1fa95f66dcda8e"
      define_method(:install) do
        bin.install "ccoverage"
      end
    end
  end

  test do
    system "#{bin}/ccoverage", "--version"
  end
end
