# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccoverage < Formula
  desc "Coverage analysis for Claude Code project configuration"
  homepage "https://github.com/ShuhaoZQGG/ccoverage"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.8/ccoverage_0.0.8_darwin_amd64.tar.gz"
      sha256 "ab813c0d0b47bb2644fefe101cc0d12a57119235ee9275f842db7f75e155f81f"

      define_method(:install) do
        bin.install "ccoverage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.8/ccoverage_0.0.8_darwin_arm64.tar.gz"
      sha256 "3698ed7b93794752a8ba6eeb48afc52f1d4eb244fde7352aac34722c94732882"

      define_method(:install) do
        bin.install "ccoverage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.8/ccoverage_0.0.8_linux_amd64.tar.gz"
      sha256 "b512dab8d437cf2381e68d21a2ca4a9fbafa551f9ec58098c9588f8350bc1422"
      define_method(:install) do
        bin.install "ccoverage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShuhaoZQGG/ccoverage/releases/download/v0.0.8/ccoverage_0.0.8_linux_arm64.tar.gz"
      sha256 "9242c1b658212f832b8ddfb1a76a75d5e682ebd8b3cc813ce7d9c68501b046e3"
      define_method(:install) do
        bin.install "ccoverage"
      end
    end
  end

  test do
    system "#{bin}/ccoverage", "--version"
  end
end
